### ISSUE TITLE
Need of compile options

### ISSUE THREAD

**Issue by danielgomezrico** [pushbit/sprockets-android#1]
Why do we need compileOptions in gradle?

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

**Comment by pushbit** [comment]
Previously this was required to use Java 7 features, such as the diamond operator, multi-catch, etc.  But it seems that explicitly declaring these options is no longer necessary, so I will remove them.

**Comment by danielgomezrico** [comment]
ok thanks :+1:
