### ISSUE TITLE
Problem using google places api

### ISSUE THREAD

**Issue by Aditya21196** [pushbit/sprockets-android#11]
hello, I was redirected to this link from this page:
>http://stackoverflow.com/questions/25954448/how-do-i-implement-google-places-autocomplete-on-a->search-widget-in-my-android-a

I have set up the library and placed the widget which is:
```
<net.sf.sprockets.widget.GooglePlaceAutoComplete
        android:id="@+id/sprockets"
        android:layout_width="match_parent"
        android:layout_height="45dp"
        android:background="#BA68C8"
        android:textSize="30sp"
        android:hint="Enter Destination"
        android:textColorHint="#CE93D8" />
```
What is the format for onPlacePickedListener? 
I simply want to implement a method called geoLocate(String place) where 'place' is the what the user picks.
Thanks

**Comment by pushbit** [comment]
Please see the [GooglePlaceAutoComplete Javadoc][1].  You can set an `OnPlaceClickListener`, which will give you all of the [available] details about the place that the user picks.  If you need additional details, you can give the `placeId` to [Places.details][2].

[1]: https://pushbit.github.io/sprockets-android/apidocs/index.html?net/sf/sprockets/widget/GooglePlaceAutoComplete.html
[2]: https://pushbit.github.io/sprockets-android/apidocs/net/sf/sprockets/google/Places.html#details%28net.sf.sprockets.google.Places.Params%29

**Comment by Aditya21196** [comment]
Thanks I was able to accomplish what I wanted with this documentation. But now I am facing a different problem. Whenever I try to complie the sprockets library, my app apk is unable to build. Then again if I remove:
>compile 'net.sf.sprockets:sprockets-android:3.0.0'
the apk gets built. What do you suggest I should do?
