### ISSUE TITLE
Question : How to send a place via an intent

### ISSUE THREAD

**Issue by hellgheast** [pushbit/sprockets-android#13]
Hello,
I'm trying to send a place as extra in an intent,of course i get the serialilazable exception about the immutables object.
Do you have any advice about that ?
Parceable would be better ?
Have a nice day,
Hellgheast

**Comment by pushbit** [comment]
`Place` is in a plain Java (not Android) library, so there isn't really an option to make it `Parcelable`.  Perhaps you can take the fields that you are interested in from `Place` (if it's not too many) and set the values as `Intent` extras (String, long, etc.)?
