### ISSUE TITLE
Minify false

### ISSUE THREAD

**Issue by danielgomezrico** [pushbit/sprockets-android#2]
Hi

I get this error on run with 

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro',
                    'proguard-sprockets.pro'

 Error:Execution failed for task ':app:dexDebug'.
 > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException:    Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java'' finished  with non-zero exit value 2

**Comment by pushbit** [comment]
`minifyEnabled` must be `true` so that ProGuard will run and remove unused methods.  Please try changing that and let me know if it fixes the issue.

**Comment by danielgomezrico** [comment]
but I have a debug build and release build, then all should be minified?

**Comment by pushbit** [comment]
Correct, all minified.  Sprockets uses and provides many different libraries and the total number of methods exceeds the current dex limit.  So we always have to use ProGuard to remove the unused methods.  For your debug build at least, you'll probably want to use `-dontobfuscate` in `proguard-rules.pro`.

**Comment by danielgomezrico** [comment]
:+1: thanks man
