### ISSUE TITLE
Google Apis

### ISSUE THREAD

**Issue by danielgomezrico** [pushbit/sprockets-android#4]
Which google apis I need to enable to use the `GooglePlaceAutoComplete`?
I´m getting `E/PlaceFilter﹕ autocomplete failed: REQUEST_DENIED`

![screen shot 2015-04-14 at 8 39 02 pm](https://cloud.githubusercontent.com/assets/76348/7150844/51304278-e2e6-11e4-9a41-5fb4220da39e.png)

**Comment by pushbit** [comment]
You need `Places API`.  See the [set up instructions][1] for more information.

[1]: https://developers.google.com/places/webservice/intro#Authentication
