### ISSUE TITLE
GooglePlaceAutoComplete imeAction not set

### ISSUE THREAD

**Issue by danielgomezrico** [pushbit/sprockets-android#5]
Hi
I have the next GooglePlaceAutoComplete but the keyboard dont show the Go action.

    <net.sf.sprockets.widget.GooglePlaceAutoComplete
                android:id="@+id/address_place_text"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="@dimen/activity_horizontal_margin"
                android:layout_marginLeft="@dimen/activity_horizontal_margin"
                android:layout_marginRight="@dimen/activity_horizontal_margin"
                android:layout_marginBottom="@dimen/activity_horizontal_margin"
                android:imeOptions="actionGo"
                sprockets:matchedSubstringColor="@color/pickup_primary_text_dark"/>

Why?

**Comment by pushbit** [comment]
I believe this is a general `AutoCompleteTextView` issue.  See [this answer][1] about changing the `inputType` to affect the action button.

[1]: https://stackoverflow.com/a/16280351/1787937

**Comment by danielgomezrico** [comment]
It worked using

   android:imeOptions="actionSearch"
                android:inputType="text"

**Comment by pushbit** [comment]
Thanks for the confirmation.
