### ISSUE TITLE
Weird LatLng

### ISSUE THREAD

**Issue by danielgomezrico** [pushbit/sprockets-android#6]
I´m using AppCompat 22.1.1 and 

 @Override public void onPlaceClick(AdapterView<?> adapterView, Place.Prediction prediction, int i) {
    // Move camera to prediction.getLatLng() 
  }

And Latitude/Logitude have -90.000000 NaN,

why?

**Comment by pushbit** [comment]
`Prediction`s don't include lat/lng values (limitation of the Google Places API).  Those methods are inherited from `Place`.  Please see [this issue][1].  Basically, you need to call `Places.details` with the `placeId` to get lat/lng (and a variety of other info).

[1]: https://github.com/pushbit/sprockets/issues/10

**Comment by danielgomezrico** [comment]
It worked, thanks. I left a gist https://gist.github.com/danielgomezrico/e1402e065b7b2ed7be84
