### ISSUE TITLE
Add G Maps Key by Static set

### ISSUE THREAD

**Issue by danielgomezrico** [pushbit/sprockets-android#7]
Hi

I have my keys on gradle.properties local file so they are not in my repository, but I can the google maps api key from that to sprockets. 

Is there any way to do this? via static class or something? 
Check parse library, you can call `Parse.init("key")` from you `Application` class or something like that.

**Comment by pushbit** [comment]
Yes, see the [Sprockets][1] Javadoc for all of the ways you can configure the library.  It sounds like you want to do something like:

```java
Sprockets.getConfig().setProperty("google.api-key", BuildConfig.GOOGLE_API_KEY);
```

And in `build.gradle`:

```groovy
buildConfigField 'String', 'GOOGLE_API_KEY', GOOGLE_API_KEY
```

The last argument comes from `gradle.properties`.  See Dining Out's [build.gradle][2] and [gradle.properties][3] for an example.

[1]: https://pushbit.github.io/sprockets-android/apidocs/index.html?net/sf/sprockets/Sprockets.html
[2]: https://github.com/pushbit/dining-out/blob/master/app/build.gradle
[3]: https://github.com/pushbit/dining-out/blob/master/app/gradle.properties

**Comment by danielgomezrico** [comment]
I tried with:

```
Sprockets.getConfig().setProperty("google.api-key", getString(R.string.base_gmaps));
        Sprockets.getConfig().setProperty("network.http-client", "okhttp");
```

and get:

```
E/PlaceFilter﹕ autocomplete failed: REQUEST_DENIED
```

**Comment by pushbit** [comment]
Does the value for `R.string.base_gmaps` work in a web request?  Try printing it out to make sure that it's the value you expect.  `REQUEST_DENIED` seems to indicate that key is invalid.

**Comment by danielgomezrico** [comment]
That´s true, it had the wrong key. Thanks
